# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:                Bootleggers ROM
tagline:             'Making you feel like 家'
description:         'Bootleggers ROM is an aftermarket firmware based on Ground Zero Open Source Project (GZOSP) and brings custom features with the most useful apps on your device.'
url:                 http://BootleggersROM.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bootleggers ROM
  url:               http://BootleggersROM.github.io

# Custom vars
version:             2.0 Beta
